### ISSUE TITLE
Issue with dmc2gym

### ISSUE THREAD

**Issue by davidoort** [KarlXing/RL-Visual-Continuous-Control#2]
Hey, I think dmc2gym is missing as a dependency. I'm also wondering what version we should use. Thanks!

**Comment by KarlXing** [comment]
Hi, thanks for the reminder. I noticed that the latest commit of dmc2gym was on Jan 24, 2022. Since this repository was developed and tested after that, I think we should use the the latest commit and you can install dmc2gym via `pip install git+git://github.com/denisyarats/dmc2gym.git `.

I'm going to update conda_env.yml to add this missing dependency and specify the commit/version for the dmc2gym and dm_control. Thanks again!

**Comment by davidoort** [comment]
Hey Karl, did you get around to doing or testing this? Thanks!

**Comment by KarlXing** [comment]
Hi David, I'm quite busy with interviews recently and plan to do the tests by early next week. Thanks :)

**Comment by KarlXing** [comment]
Hi David, I updated conda_env.yml to add missed dependency and version control. Feel free to reopen the issue and let me know if you meet other problems.
